ezsystems/BehatBundle

- Context/EzContext.php
> Required by ezsystems/ezpublish-community#226
> Removed legacy references

- Context/Browser/SubContext/CommonActions.php
This adds sentences/methods to deal with fields in BrowserContext
> Improved Field handling in Browser Context

- Context/Browser/SubContext/CommonActions.php
- Helper/Xpath.php
To unblock https://github.com/ezsystems/ezplatform/pull/34
> Fix Mink 1.6 compatability issue

- Context/EzContext.php
- Context/Object/BasicContent.php
- ObjectManager/BasicContent.php
Auxiliary sentences used to create basic dummy content to be used for BDD testing
Related jira to Issues:
https://jira.ez.no/browse/QA-436
https://jira.ez.no/browse/QA-437
https://jira.ez.no/browse/QA-438
> QA-436 / QA-437 / QA-438 Basic content creation sentences

- ObjectManager/BasicContent.php
BasicContent Context did not had the destroy function implementation needed to clean the object created by the tests
> Added missing destroy function for BasicContext

- Context/Browser/SubContext/CommonActions.php
- Context/EzContext.php
- Context/Object/Role.php
- ObjectManager/Role.php
Basic operations needed to test RoleUI with behat BDD tests
> Basic role operations for usage with platformUI behat tests

- Context/Browser/SubContext/CommonActions.php
- Context/Object/FieldType.php
Added two minor fixes:
* Added missing sentence "I see field with label" implantation
* Fixed letter casing problem in some sentences
> Minor fixes in the Sentences and Implementation

- ObjectManager/Role.php
Minor change to how role is created to take in count the Role versioning.
> Added missing Role version compatibility

- ObjectManager/FieldType.php
Ref: https://github.com/ezsystems/PlatformUIBundle/pull/416
> Util methods to get field identifier and contentId, minor fixes

- Context/Resolver/AnnotationArgumentResolver.php
- Resources/config/services.yml
- ServiceContainer/EzBehatExtension.php
- behat_suites.yml
- doc/Writing Tests.md
Replaces #44
Resolves arguments using annotations and let Symfony2BehatExtension handle services requirements.
> Behat ArgumentResolver for Context service injection 

- Helper/EzAssertion.php
Added assert element not found assertion to EzAssertion Helper
> Add assertElementNotFound EzAssertion method

- .travis.yml
- composer.json
In order to unblock #60 which will allow us to upgrade kernel ^6.7 to phpunit 5 as well.
> [WIP] Fix travis

- composer.json
This is the first step to migrate PHPUnit to newer versions on eZ repos.
> Enable PHPUnit 5

- .travis.yml
To prepare for #63 to make sure it works on both versions.
> [Travis] Setup to run some of the tests on PHP 5.6

- composer.json
It will be released in two weeks time :)
> Allow installation of PHPUnit 7.0

- .travis.yml
- composer.json
- src/lib/API/Context/LimitationParser/ContentTypeLimitationParser.php
Currently the CS fixer job is failing because of Composer memory issues.
Also, the notifications on Travis are not working.
> Fix Composer memory issue and notifications

- .travis.yml
- bin/.travis/prepare_ezplatform.sh
Reorganizing .travis.yml file, introducing ezbehat script usage, change install script to match the other repos.
Related PRs:
ezsystems/BehatBundle#77
ezsystems/ezplatform-admin-ui#992
ezsystems/ezplatform-page-builder#344
ezsystems/ezplatform-form-builder#162
ezsystems/date-based-publisher#107
ezsystems/ezplatform-admin-ui-modules#189
> EZP-30315 [Travis] Standarize and clean up travis configurations across the repositories

- behat_suites.yml
- features/configuration.feature
- features/user_roles.feature
- src/bundle/Resources/config/services.yaml
- src/bundle/Resources/config/services/fieldtype_data_providers.yaml
- src/bundle/Resources/config/services/limitation_parsers.yaml
- src/lib/API/Context/LimitationParser/ContentTypeLimitationParser.php
- src/lib/API/Context/LimitationParser/LanguageLimitationParser.php
- src/lib/API/Context/LimitationParser/LimitationParserInterface.php
- src/lib/API/Context/LimitationParser/LocationLimitationParser.php
- src/lib/API/Context/LimitationParser/NewSectionLimitationParser.php
- src/lib/API/Context/LimitationParser/NewStateLimitationParser.php
- src/lib/API/Context/LimitationParser/ObjectStateLimitationParser.php
- src/lib/API/Context/LimitationParser/OwnerLimitationParser.php
- src/lib/API/Context/LimitationParser/ParentContentTypeLimitationParser.php
- src/lib/API/Context/LimitationParser/ParentDepthLimitationParser.php
- src/lib/API/Context/LimitationParser/ParentOwnerLimitationParser.php
- src/lib/API/Context/LimitationParser/ParentUserGroupLimitationParser.php
- src/lib/API/Context/LimitationParser/SectionLimitationParser.php
- src/lib/API/Context/LimitationParser/SiteaccessLimitationParser.php
- src/lib/API/Context/LimitationParser/UserGroupLimitationParser.php
- src/lib/API/Context/LimitationParser/WorkflowStageLimitationParser.php
- src/lib/API/Context/LimitationParser/WorkflowTransitionLimitationParser.php
- src/lib/API/Context/ObjectStateContext.php
JIRA: https://jira.ez.no/browse/EZP-30597
This PR adds support to BehatBundle for all existing Limitations mentioned in https://doc.ezplatform.com/en/latest/guide/limitation_reference/
Also added an Object State Context, so that the Limitation can be tested.
Example:
```
Given Language "Polski" with code "pol-PL" exists
And Object State Group "Colors" with identifier "colors" exists
| objectStates |
| red          |
| green        |
And I create a role "complexRole"
And I add policy "content" "create" to "complexRole" with limitations
| limitationType      | limitationValue      |
| Subtree             | /Media,/Media/Images |
| Content Type        | Article,Folder       |
| Language            | pol-PL,eng-GB        |
| Location            | /Media,/Media/Images |
| Parent Content Type | …
```
> EZP-30597: Add limitation parsers

- composer.json
- src/lib/Browser/Context/Hooks.php
- src/lib/Core/Log/LogFileReader.php
- tests/Core/Log/LogFileReaderTest.php
This PR is doing the same thing as https://github.com/ezsystems/ezplatform-admin-ui/pull/1046 , but for 3.0.
There are tests added(I didn't want to introduce a new dependency in AdminUI, but we can do this here).
> Added Behat debug info

- .travis.yml
- composer.json
- src/lib/Browser/Context/Hooks.php
- src/lib/Core/Log/LogFileReader.php
- tests/Core/Log/LogFileReaderTest.php
Adding https://github.com/ezsystems/BehatBundle/pull/90 once again, correctly this time - 
required PR: https://github.com/ezsystems/ezplatform/pull/443
Also adding a job running Selenium tests to make sure this issue does not happen again.
> Reintroduce debug info for Selenium Behat tests

- src/lib/Core/Behat/AnnotationArgumentResolver.php
"Merging" changes from https://github.com/ezsystems/ezpublish-kernel/pull/2750 to 3.0
> EZP-30884: Added support for class name as service id

- src/lib/Core/Behat/ArgumentParser.php
Fixing wrong EnvironmentConstants usage that should have been changed during upstream merge.
> Fixed EnvironmentConstants usage

- .php_cs
- composer.json
JIRA: https://jira.ez.no/browse/EZP-31108
> EZP-31108: Provided common PHP CS Fixer configuration for internal useInternal code style

- src/lib/Core/Environment/EnvironmentConstants.php
Added detection if the current environment is an Enterprise one.
Used in https://github.com/ezsystems/ezplatform-content-forms/pull/6
> Added checking if current environment is enterprise edition

- .travis.yml
- Context/ConfigurationContext.php
- behat_suites.yml
- features/setup/siteaccessMatcher/CompoundMapURIMapHost.feature
- features/setup/siteaccessMatcher/MapHost.feature
- features/setup/siteaccessMatcher/MapURI.feature
- features/setup/siteaccessMatcher/URIElement.feature
https://jira.ez.no/browse/EZP-29112
TODO before merge:
> EZP-29112 Implement scenarios for Site Access matching

- .travis.yml
- src/lib/API/ContentData/ContentDataProvider.php
Done as part of jira.ez.no/browse/ EZP-31078
Adjusting tests to changes done in https://github.com/ezsystems/ezpublish-kernel/pull/2839
Also trying to fix Slack notification, which never worked for this bunde 😉
> EZP-31078: Adapted tests for FieldDefinitionCollection

- Command/GetPullRequestDataCommand.php
JIRA: https://jira.ez.no/browse/EZEE-2994
Changed the way how composer.json file is downloaded. Previously it was a simple `file_get_contents` call, now we use the official GitHub API for that: https://developer.github.com/v3/repos/contents/#get-contents
Before the fix:
```
php bin/console ezplatform:tools:get-pull-request-data https://github.com/ezsystems/ezplatform-workflow/pull/112 <token>
In GetPullRequestDataCommand.php line 120:
Warning: file_get_contents(https://raw.githubusercontent.com/ezsystems/ezplatform-workflow/master/composer.json): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found
```
After the fix:
```
php bin/console ezplatform:tools:get-pull-request-data https://github.com/ezsystems/ezplatform-workflow/pull/109 <token> …
```
> EZEE-2994: Changed regression script to use GitHub API to download composer.json file

- features/setup/multirepository/multirepository.feature
https://github.com/ezsystems/ezplatform-ee/pull/127 added a new database connection.
Our multirepository setup overwrites the existing connections (breaking the default one and adding a new one), so we need to add it here as well.
> Added SiteFactory connection to multirepository setup

- bin/.travis/trigger_ci.sh
Fixed typo in regression script
> Fixed typo in regression script

- src/bundle/Resources/config/services/fieldtype_data_providers.yaml
- src/lib/API/ContentData/FieldTypeData/ImageAssetDataProvider.php
> JIRA: https://jira.ez.no/browse/EZP-30543
> EZP-30543: Removed Dynamic Settings functionality from kernel

- src/lib/Browser/Context/Hooks.php
- src/lib/Core/Log/TestLogProvider.php
Upstream merge of https://github.com/ezsystems/ezplatform-admin-ui/pull/1271
> [DON'T MERGE] [Behat] Refactored displaying logs for Allure

- src/lib/Browser/Context/Hooks.php
- src/lib/Core/Log/TestLogProvider.php
Running tests for changes from https://github.com/ezsystems/ezplatform-admin-ui/pull/1347 when merging upstream
> [DON'T MERGE] [Behat] Added browser log caching

- bin/.travis/trigger_ci.sh
https://jira.ez.no/browse/EZP-31464
I have added a script which should wait for user confirmation to proceed regression script.
> [Behat] Regression script should wait for Enter when asking for confirmation

- .travis.yml
https://jira.ez.no/browse/EZP-31613
Regenerated Slack integration after workspace name change.
> [Travis] Changed notification key after rebranding

- src/lib/Browser/Factory/ElementFactory.php
- src/lib/Browser/Factory/PageObjectFactory.php
- src/lib/Core/Environment/EnvironmentConstants.php
- src/lib/Core/Environment/InstallType.php
JIRA: https://jira.ez.no/browse/EZEE-3222
Added changes in behatBundle to accomodate Behat automation for eZCommerce.
Mainly added COMMERCE InstallType.
> [BEHAT] added changes for automation on eZCommerce

- API/Facade/ContentFacade.php
- API/Facade/TrashFacade.php
- Context/Object/TrashContext.php
- Helper/ArgumentParser.php
- Resources/config/services.yml
I added Trash facade and context and method helps getting content by location URL
> EZEE-3155: added trash context

- API/Facade/ContentTypeFacade.php
- Resources/config/services.yml
JIRA: https://jira.ez.no/browse/EZP-32102
Making sure that the Content Type can be loaded after it's created (see the JIRA issue for more details when it might go wrong).
> EZP-32102: Added check that Content Type can be loaded from a Group after creation

- src/bundle/Command/CreateExampleDataManagerCommand.php
> JIRA: -
Example output: https://gist.github.com/adamwojs/af7a4462606267d7be8384eae22051d4
> Redirected stderr from child processes to ibexa:behat:generate-items in case of failure

- features/personas/change_password.feature
**JIRA**: https://issues.ibexa.co/browse/IBX-405
Behatbundle part of the test checking whether the user/password policy works correctly.
Related PRs: 
https://github.com/ezsystems/ezplatform-admin-ui/pull/1764
https://github.com/ezsystems/ezplatform-page-builder/pull/762
> IBX-405: Behat coverage for changing user password

- src/lib/Browser/Factory/ElementFactory.php
> JIRA: [IBX-100](https://jira.ez.no/browse/IBX-100)
- Added element factory
> [Behat] IBX-100 Add scenario for user creation in Commerce

- src/lib/Browser/Locator/CSSLocatorBuilder.php
- src/lib/Browser/Page/LoginPage.php
- src/lib/Browser/Page/RedirectLoginPage.php
https://issues.ibexa.co/browse/IBX-264
The same things as in https://github.com/ezsystems/ezplatform-admin-ui/pull/1803
> [Behat] Fixed PHPUnit 9 deprecations and class usage casing

- behat_ibexa_commerce.yaml
- behat_ibexa_content.yaml
- behat_ibexa_experience.yaml
- behat_ibexa_oss.yaml
JIRA: https://issues.ibexa.co/browse/IBX-580
Added missing contexts.
> IBX-580: Added contexts for regression suites

- behat_ibexa_commerce.yaml
- behat_ibexa_content.yaml
- behat_ibexa_experience.yaml
- behat_ibexa_oss.yaml
JIRA: https://issues.ibexa.co/browse/IBX-836
> IBX-836: Renamed RightMenu and RightMenuContext

- behat_ibexa_commerce.yaml
- behat_ibexa_experience.yaml
https://github.com/ezsystems/ezplatform-page-fieldtype/pull/200
> IBX-892: Moved Behat context out of tests namespace

- behat_ibexa_commerce.yaml
- behat_ibexa_content.yaml
- behat_ibexa_experience.yaml
- src/lib/Subscriber/CreateContentDraft.php
- src/lib/Subscriber/EditContent.php
- src/lib/Subscriber/PublishDraft.php
- src/lib/Subscriber/PublishInTheFuture.php
- src/lib/Subscriber/Review.php
https://github.com/ezsystems/ezplatform-workflow/pull/209
> IBX-892: Moved Behat Workflow package into lib from tests

- behat_ibexa_commerce.yaml
> JIRA: [IBX-698](https://issues.ibexa.co/browse/IBX-698)
I've added new test scenario to handle case with updating eCommerce configuration settings.
> [Behat] IBX-698 Updating ecommerce configuration settings

- composer.json
| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | [IBX-1171](https://issues.ibexa.co/browse/IBX-1171)
| **Type**                                   | chore
| **Target Ibexa version** | `v4.0`
| **BC breaks**                          | no
Prepare main branch to 4.0 release (unification of package versions across codebase)
> [Composer] Bumped dependencies for 4.0 version

- behat_ibexa_commerce.yaml
- behat_ibexa_content.yaml
- behat_ibexa_experience.yaml
- behat_ibexa_oss.yaml
- src/lib/Core/Context/ConfigurationContext.php
Adjusting config file paths to the rebranding process.
Requires:
https://github.com/ibexa/admin-ui/pull/58
https://github.com/ibexa/commerce-shop/pull/10
*Contains TMP commit, needs rebase before merge*
> Adjusted config files paths

- behat_ibexa_commerce.yaml
- src/lib/Browser/FileUpload/FileUploadHelper.php
Tickets | https://issues.ibexa.co/browse/IBX-978
-- | --
I've added new test scenario to verify that proper product page is loaded for product with product variants while "User interface for ordering variants" setting is set to B2B.
**Regression passed:**
Note that failed job (ContentIntegration.feature) isn't related with my changes. It fails on nightly builds as well.
Build: https://app.travis-ci.com/github/ezsystems/ezplatform-page-builder/builds/241768320
> [Behat] IBX-978 Verify product page on frontend

- behat_ibexa_commerce.yaml
- behat_ibexa_content.yaml
- behat_ibexa_experience.yaml
- behat_ibexa_oss.yaml
- behat_suites.yml
- features/setup/loginMethods/email_provider.feature
- src/lib/API/Context/UserContext.php
- src/lib/API/Facade/UserFacade.php
- src/lib/Browser/Locator/VisibleCSSLocator.php
**JIRA**: https://issues.ibexa.co/browse/IBX-1095
Things done:
- introduced setup scenario modifying security.yaml (adding chain with both username and email providers)
- added support for known (not random) email in createUser
- improved error handling for driver
Related PR: https://github.com/ezsystems/ezplatform-user/pull/103
> IBX-1095: Behat coverage for login scenarios with email provider

- composer.json
- src/lib/Core/Context/FileContext.php
This PR adds a Step that allows to apply given patch.
It's needed by https://github.com/ezsystems/ezplatform-http-cache/pull/165 - we used to apply a patch to enable Symfony Proxy directly in Travis setup, now it will be done by tests.
Output when the step fails:
```
Given I apply the patch                        # EzSystems\Behat\Core\Context\FileContext::patchFile()
"""
From fe9ff7bd801f978cfc50aae0411bb3eefdd3059a Mon Sep 17 00:00:00 2001
From: =?UTF-8?q?Marek=20Noco=C5=84?= <mnocon@users.noreply.github.com>
Date: Wed, 7 Jul 2021 15:29:57 +0200
Subject: [PATCH] Enabled Symfony Reverse Proxy
---
public/index.php | 7 ++++++-
1 file changed, 6 insertions(+), 1 deletion(-)
diff --git a/public/index.php b/public/index.php
index 9982c21..03ac40a 100644
--- a/public/index.php
+++ …
```
> Added patching

- src/lib/API/ContentData/FieldTypeData/ImageAssetDataProvider.php
https://issues.ibexa.co/browse/IBX-2153
> IBX-2153: Moved ConfigResolverInterface into contracts

- .github/workflows/pr-assign.yaml
| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | IBX-1734
| **Type**                                   | improvement
| **Target Ibexa version** | `2.5`
| **BC breaks**                          | no
| **Doc needed**                       | no
This will introduce pr-assigner workflow to the repository that will automatically assign newly opened PRs to appropriate persons/teams, based on the external configuration.
> IBX-1734: Added PR assigner workflow

- src/lib/API/ContentData/FieldTypeData/RichTextDataProvider.php
Adjusting data provider to the changes in https://github.com/ibexa/fieldtype-richtext/pull/31
> Adjusted RichtextDataProvider to the rebranding changes
