ezsystems/BehatBundle

Context/EzContext.php
Context/Object/FieldType.php
ObjectManager/FieldType.php

Base implementation for the FieldType sentences. Mostly prerequisites are implemented here on the Behat level, in conjunction with the PlatformUICore ezsystems/PlatformUIBundle#230 implements the sentences for the FieldTypes as in ezsystems/PlatformUIBundle#211.

FieldType context

---

Context/EzContext.php

> Required by ezsystems/ezpublish-kernel#1401
This matches the default siteaccess from the config instead of a hardcoded one. Makes it possible to run behat with any kind of install.

Made EzContext use default SA from settings

---

ObjectManager/BasicContent.php

PR #34 introduced two minor bugs:
* A call to the method `createContentDraft()` as the wrong parameters order
* A call to the method `createContentDraft()` was not wrapped in a `sudo()`

Bug fix: ObjectManager/BasicContent draft support

---

Context/Object/BasicContent.php

This PR resolves `BehatBundle` part of https://jira.ez.no/browse/EZP-24925
Just some more conversion from XmlText to RichText.

Implement EZP-24925: Extract XmlText field type out of kernel into separate repository

---

Context/Browser/SubContext/Authentication.php
Context/Browser/SubContext/CommonActions.php

This PR removes some of the methods in the Browser Context that were not being used by any Behat test.

Deprecate unused/moved methods from Browser Context

---

Context/Object/FieldType.php
ObjectManager/FieldType.php

Add Textline fieldtype default values, internal name and validator support in Fields Context. Required to run test related to Textline fields.

Add Textline fieldtype support for Behat tests

---

Context/RepositoryContext.php
Context/Resolver/AnnotationArgumentResolver.php
ServiceContainer/EzBehatExtension.php

As decided BehatBundle is to be deprecated and separated between the kernel and platformUI bundle. The idea is to make the Behat easier to maintain, having less repo dependencies should help releases and versions also.
Added deprecation Doc to the classes to be deprecated in the following PRs:
* https://github.com/ezsystems/ezpublish-kernel/pull/1584
* https://github.com/ezsystems/ezpublish-kernel/pull/1585
* https://github.com/ezsystems/ezpublish-kernel/pull/1586

Deprecate Behat classes that will be moved to kernel

---

Context/Object/User.php
Context/Object/UserGroup.php
ObjectManager/Base.php
ObjectManager/FieldType.php

Random numbers used for names and identifiers were being generated with a small interval which caused collisions sometimes resulting in test failures.  Before we were using the `rand` function and now we use the `uniqid` function to generate the unique identifiers, this should make collision extremely rare or not happen at all.

Improve unique genarated values for names and identifiers

---

Context/Object/FieldType.php

The syntax `Given a Content Type with an :fieldType field exists` is wrong in some cases. This PR adds the possibility to use `Given a Content Type with a :fieldType field exists` as well.

Add right syntax to FieldType sentences

---

Context/EzContext.php
Context/Object/ContentType.php
ObjectManager/Role.php

Unblocks [EZP-24842](https://jira.ez.no/browse/EZP-24842)
----
While executing Behat scenarios for eZ Platform running on PostgreSQL (see  [EZP-24842](https://jira.ez.no/browse/EZP-24842)) I've found some inconsistencies in identifier letters case and I've chosen simplest way to fix them. 
Though this is related to `v2` support of PostgreSQL, we can fix it without risk for current version of this bundle as eZ Platform `2.0` also uses it and for MySQL due to `utf8_general_ci` collation it does not matter.
**TODO**:
*all scenarios use `administrator` Role name while default setup provides `Administrator` Role, which matters for PostgreSQL*

EZP-24842: [PostgreSQL] Fixed identifier letters case inconsistencies

---

.travis.yml
ObjectManager/Role.php
bin/.travis/prepare_behat.sh
bin/.travis/prepare_behat_v2.sh
composer.json

JIRA Ticket: https://jira.ez.no/browse/EZP-25780
Looks like Stash has problems with concurrent operations happening in Filesystem cache, it was reported to them: https://github.com/tedious/Stash/issues/359 (also, similar issue: https://jira.ez.no/browse/EZP-29257)
Given that:
1) this issue occurs only in tests for us
2) The main purpose of the test (it's possible to delete a Role using PlatformUI) is still met (and tested)
3) it was reported more than 2 years ago
I think we can silence this warning. Handling it is important, because it causes PlatformUI 1.7 and 1.13 tests to randomly fail, which decreases the efficiency of our CI.
~~It's `WIP`, because I still have to test it on Travis.~~ I've used https://github.com/ezsystems/PlatformUIBundle/pull/988 for testing.
First commit is the …

EZP-25780: Ignore PHP warnings when clearing cache.

---

Context/Object/User.php
Context/Object/UserGroup.php
ObjectManager/FieldType.php

Implements https://jira.ez.no/browse/EZP-30008
Use `prefix` and `more_entropy` wherever possible.
2nd commit fixes typo in a variable name.
See also https://github.com/ezsystems/ezpublish-kernel/pull/2523 and https://github.com/ezsystems/repository-forms/pull/271

EZP-30008: More unique uniqid()

---

ObjectManager/FieldType.php

The generated name is used as Content Type identifier, which cannot contain the `.` symbol. 
Using the dot breaks AdminUI tests, which use BehatBundle to create Content Types - example failure: https://res.cloudinary.com/ezplatformtravis/image/upload/v1547823290/screenshots/vendor_ezsystems_ezplatform-admin-ui_features_contenttypefields_feature_24_wwqmm1.png

Removed the dot in Content Type identifier

---

Context/Object/User.php

The recent changes in BehatBundle (https://github.com/ezsystems/BehatBundle/pull/72) uncovered an issue in PlatformUI: https://jira.ez.no/browse/EZP-30186
This is causing the current 1.7 builds to fail, for example: https://travis-ci.org/ezsystems/ezplatform/jobs/499512773
Screenshot from Travis: https://res.cloudinary.com/ezplatformtravis/image/upload/v1551311404/screenshots/5c77222c73287811074211-vendor_ezsystems_platform-ui-bundle_features_users_users_feature_7_acbp3s.png
I think that the priority of this issue is rather low (1.7 has been released long time ago and nobody reported it), so for me it makes sense to adjust the tests and generate shorter usernames (and unblock the build so that we will be notified when something serious happens).
Uniqid with more_entropy is guaranteed to …

Do not generate usernames longer than 15 characters

---

Context/EzContext.php
Context/Object/User.php
Features/user.feature
ObjectManager/User.php

After https://github.com/ezsystems/ezpublish-kernel/pull/2570 the repository-forms tests started failing with:
```
And there is a User with name "testuser" in "Members" group             # EzSystems\BehatBundle\Context\EzContext::iHaveUserInGroup()
eZ\Publish\Core\Base\Exceptions\UserPasswordValidationException: Argument 'password' is invalid: Password doesn't match the following rules: User password must be at least 10 characters long, User password must include at least one upper case letter, User password must include at least one number in vendor/ezsystems/ezpublish-kernel/eZ/Publish/Core/Repository/UserService.php:426
Stack trace:
```
(https://travis-ci.org/ezsystems/ezplatform/jobs/509658540)
as the password equal to username does not meet the requirements. Adjusting it so that it …

Change passwords used in tests

---

bin/ezbehat
composer.json

Script that covers all the cases of running behat tests in eZ Systems repositories on Travis CI. Should be self-explanatory, if not - I'm here to help. 
Together with merging that script we'll be able to remove `get_behat_features.sh` script from meta-repos.

EZP-30315 [Travis] Standarize and clean up travis configurations across the repositories

---

bin/ezbehat

Not all of our tests are ready to run with the `--strict` option (eg. repository-forms or some kernel tests). These tests have some undefined steps and we're not planning to change that in the near future, but at the same time, this is not a desirable situation.
Because of that, I decided to add the option `--non-strict` to the `ezbehat` script, to specify strictness only in non-default situations.

EZP-30315 - add parametrization of `strict` option

---

.travis.yml
behat_suites.yml
bootstrap.php
composer.json
features/configuration.feature
phpunit.xml
src/bundle/Resources/config/services.yml
src/lib/Core/Configuration/ConfigurationEditor.php
src/lib/Core/Context/ConfigurationContext.php
tests/Core/Configuration/ConfigurationEditorTest.php

JIRA: https://jira.ez.no/browse/EZP-30540
This PR adds ability to manage configuration (examples here use ezplatform.yml, but `ConfigurationEditor` will work for any YAML file.
Example after executing added scenarios: https://gist.github.com/mnocon/505dbfaa58e004d09214b6180f2c520e
This does not clear cache (and I don't think it should), meaning that after running the scenarios you need to run `composer run post-install-cmd` manually for the changes to start working.

EZP-30540: Add ability to manage configuration using BehatBundle

---

src/bundle/BehatExtension.php
src/bundle/Command/CreateLanguageCommand.php
src/bundle/Command/TestSiteaccessCommand.php
src/bundle/Controller/ExceptionController.php
src/bundle/Resources/config/extension.yml
src/bundle/Resources/config/routing.yml
src/bundle/Resources/config/services.yml
src/bundle/Resources/views/tests/dump.html.twig
src/lib/Core/Behat/AnnotationArgumentResolver.php

JIRA: https://jira.ez.no/browse/EZP-30539
This PR adds parts of PlatformBehatBundle from https://github.com/ezsystems/ezpublish-kernel/pull/2642
Things ported:
- Behat extension. It's useful, though if we will be able to switch to Symfony4Extension we will be able to drop it as well
- Controller, Twig template, Commands  - it's a good start to have these things here and slowly grow the base of real examples how to customise the product (and test the behaviour by the way)
Removed:
- Deprecation suppression - I believe it's better to handle each deprecation separately, not with a general "suppress all" tool (also it turned out it wasn't needed)
- RepositoryContext trait - this is achieved with TestContext now

EZP-30539: Move Platform Behat Bundle to BehatBundle

---

src/lib/API/ContentData/FieldTypeNameConverter.php
src/lib/Browser/Context/BrowserContext.php
src/lib/Browser/Context/Hooks.php
src/lib/Browser/Element/Element.php
src/lib/Browser/Factory/ElementFactory.php
src/lib/Browser/Factory/PageObjectFactory.php
src/lib/Browser/Filter/BrowserLogFilter.php
src/lib/Browser/Page/Page.php
src/lib/Browser/Page/Preview/FolderPreview.php
src/lib/Browser/Page/Preview/PreviewPage.php
src/lib/Browser/lib/drag-mock.js
src/lib/Core/Behat/TableNodeExtension.php
src/lib/Core/Environment/Environment.php
src/lib/Core/Environment/EnvironmentConstants.php
src/lib/Core/Environment/InstallType.php
tests/Browser/Filter/BrowserLogFilterTest.php
tests/Core/Behat/ExtendedTableNodeTest.php
tests/Core/Configuration/ConfigurationEditorTest.php

JIRA: [EZP-30668](jira.ez.no/browse/EZP-30668)
Moving core AdminUI test classes to BehatBundle.
Requires:
https://github.com/ezsystems/ezplatform-page-builder/pull/356
https://github.com/ezsystems/ezplatform-form-builder/pull/171
https://github.com/ezsystems/date-based-publisher/pull/114
https://github.com/ezsystems/flex-workflow/pull/132
https://github.com/ezsystems/repository-forms/pull/300
https://github.com/ezsystems/ezplatform-admin-ui/pull/1020
https://github.com/ezsystems/ezplatform-ee-demo/pull/148
Moved:
- `EzSystems\EzPlatformAdminUi\Behat\PageElement\Element` -> `EzSystems\Behat\Browser\Element\Element`
- `EzSystems\EzPlatformAdminUi\Behat\PageElement\ElementFactory` -> `EzSystems\Behat\Browser\Factory\ElementFactory`
- …

EZP-30668: move core tests classes from AdminUI to BehatBundle

---

src/lib/API/Facade/ContentTypeFacade.php

Something that was missed in https://github.com/ezsystems/BehatBundle/pull/87 - this has to be changed to the refactored Converter, otherwise the tests are failing with: 
```
Fatal error: Call to undefined method EzSystems\EzPlatformAdminUi\Behat\PageElement\Fields\EzFieldElement::getFieldInternalNameByName() (Behat\Testwork\Call\Exception\FatalThrowableError)
```
Example: https://travis-ci.org/ezsystems/BehatBundle/jobs/554585793

EZP-30668: Refactored tests to use the extracted fieldtype converter

---

src/lib/Browser/Context/Hooks.php
src/lib/Core/Environment/Environment.php

Another issue detected when working on https://github.com/ezsystems/ezplatform-page-builder/pull/374
Currently tests are not running correctly on ee-demo, because the install type is not correctly set. This is because the installer service definition has changed.
Installer service definitions:
https://github.com/ezsystems/ezplatform-ee-demo/blob/master/config/services/installer.yaml
https://github.com/ezsystems/ezplatform-ee-demo/blob/2.5/app/config/services/installer.yml#L7
We have to adjust for that (changing from `app.installer.ee-demo_installer` to `App\Installer\PlatformEEDemoInstaller`).
But this is not enough, as the service is now private by default - to get it directly from the container we have to use the test container (similar as it was in …

Fix EE-DEMO type detection

---

src/lib/Browser/Factory/ElementFactory.php
src/lib/Browser/Factory/PageObjectFactory.php
src/lib/Core/Environment/EnvironmentConstants.php

As an ongoing work on https://github.com/ezsystems/ezplatform-page-builder/pull/374, now the error is:
```
Given I am logged as admin # EzSystems\EzPlatformAdminUi\Behat\BusinessContext\AuthenticationContext::iAmLoggedAs()
Behat\Testwork\Call\Exception\FatalThrowableError: Fatal error: Class 'Tests\AppBundle\Behat\PageObject\DemoEnterprisePageObjectFactory' not found in vendor/ezsystems/behatbundle/src/lib/Browser/Factory/PageObjectFactory.php:72
```
This is caused by https://github.com/ezsystems/ezplatform-ee-demo/pull/150, which changed namespaces for all classes in AppBundle (from `/AppBundle/` to `/App`/)/.
Moved files:
https://github.com/ezsystems/ezplatform-ee-demo/blob/master/tests/App/Behat/PageElement/DemoEnterpriseElementFactory.php …

Adjusted namespaces after Demo has been adapted for 3.0

---

Context/Browser/SubContext/CommonActions.php

JIRA: https://jira.ez.no/browse/EZP-30830
In https://github.com/ezsystems/BehatBundle/pull/92 I did some "search and replace" refactoring for PHPUnit (Assertion -> Assert), but it turned out too broad - bringing it back as it's supposed to be used. BTW this is causing Travis builds to fail for 2.5, see: https://travis-ci.org/ezsystems/ezplatform/jobs/575619287
File before changes, for reference: https://github.com/ezsystems/BehatBundle/blob/6.5/Context/Browser/SubContext/CommonActions.php

EZP-30830: Fix usage of EzAssertion

---

.php_cs
.travis.yml
API/Facade/ContentTypeFacade.php
API/Facade/UserFacade.php
Context/Api/LimitationParser/LocationLimitationParser.php
Context/Object/ContentTypeContext.php
Context/Object/RoleContext.php
Context/Object/UserContext.php
Features/personas/subtree_editor.feature
Features/user.feature
Helper/ArgumentParser.php
Resources/config/services.yml
Resources/config/services/limitation_parsers.yaml
behat_suites.yml
tests/Helper/ArgumentParserTest.php

JIRA: https://jira.ez.no/browse/EZP-30884
This PR:
1) adds some missing config options for cs-fixer (for reference: https://github.com/ezsystems/ezpublish-kernel/blob/7.5/.php_cs)
2) adds support for assigning user to role with limitations
3) adds a new personas suite with 1 Persona: SubtreeEditor
SubtreeEditor feature:
1) I've given him read/create/edit/publish access only to part of a Subtree, with required permissions added so that he can use Content Tree and PageBuilder
2) I've created Content Items that he will be interacting with (also an another, new User so that he can use flex-workflow and send him something for review)
you can get all required dependencies using:
git clone github.com/mnocon/ezplatform.git -b EZP-30884-implement-user (ezplatform)
git clone …

Implemented setup for subtreeEditor

---

src/lib/Core/Context/ConfigurationContext.php

In https://jira.ez.no/browse/EZP-30636 we've switched the extension name from `ezpublish` to `ezplatform`, we should reflect the changes here as well.

Updated extension name

---

src/bundle/Resources/config/services.yaml
src/bundle/Resources/views/tests/dump.html.twig
src/bundle/Templating/Twig/PHPTypeExtension.php

This PR adds a Twig extension that displays variables and their type in Twig template and uses it in dump.html.twig
Twig extension code is based heavily on an example provided by @adamwojs , I don't think we need to expand it further right now.
It will be used in https://github.com/ezsystems/ezpublish-kernel/pull/2887 . How the template looks:

Added Twig PHPType extension

---

features/examples/configuration.feature

Done as part of https://jira.ez.no/browse/EZEE-2928
Merging:
- 2.5 still uses `ezpublish` key - https://github.com/ezsystems/ezplatform/blob/2.5/app/config/ezplatform.yml#L1 .Needs to be changed to `ezplatform` when merging upstream: https://github.com/ezsystems/ezplatform/blob/master/config/packages/ezplatform.yaml#L35
Description:
Current example relies on EE (page_builder setting), this PR tries to make an example that can be run using open source version.
This is required by: https://github.com/ezsystems/ezplatform/pull/485

EZEE-2928: Removed dependency on EE in examples

---

features/examples/configuration.feature

Follow-up to https://github.com/ezsystems/BehatBundle/pull/117, because I focused too much on the workflow test and missed the page_builder mention 🙈 
This time I've added the dependency to https://github.com/ezsystems/ezplatform/pull/485 and it's green, so this should be the last PR in the series.

EZEE-2928: Removed PageBuilder from examples

---

.travis.yml
features/examples/configuration.feature

Travis failure: https://travis-ci.org/ezsystems/ezplatform/jobs/626869956?utm_medium=notification&utm_source=slack
In 3.0 we've changed the main config key from `ezpublish` to `ezplatform`. This change can be forward-compatible (https://github.com/ezsystems/ezplatform-core/pull/11), but it requires enabling EzPlatformCoreBundle in AppKernel (`new EzSystems\EzPlatformCoreBundle\EzPlatformCoreBundle(),`).
This bundle is not enabled by default (see: https://github.com/ezsystems/ezplatform/blob/2.5/app/AppKernel.php), meaning we cannot use that and have to use `ezpublish` key.
Also changing how the examples are run (they should be run in standard mode, not parallel).

Changed configuration key to ezpublish from ezplatform

---

Resources/encore/ez.config.manager.js
Resources/public/js/scripts/drag-mock.js
doc/features.md

JIRA: https://jira.ez.no/browse/EZEE-2950
Doc this is based on: https://doc.ezplatform.com/en/latest/guide/bundles/#configuration-from-a-bundle
Green build with all tests passing: https://github.com/ezsystems/ezplatform-page-builder/pull/477
Companion PR, removing the code from AdminUI: https://github.com/ezsystems/ezplatform-admin-ui/pull/1201
Changing how the dragMock library is loaded - now it's added to the Page automatically in the `behat` Symfony env, which should make the tests a lot faster (there is no need to load the library for every drag and drop interaction separately).
@dew326 If you could please have a look at the `ez.config.manager.js` file, as I'm pretty sure it's not perfect 😄 I had to make sure page-builder and form-builder entries are present, otherwise this would fail …

EZEE-2950: Inject drag-mock using Webpack Encore

---

features/examples/content.feature
src/lib/API/ContentData/FieldTypeNameConverter.php
src/lib/API/Context/ContentTypeContext.php

JIRA: https://jira.ez.no/browse/EZP-31311
Required by: https://github.com/ezsystems/ezplatform-admin-ui/pull/1228
Adding the possibility to create Content Types with `ezcontentquery` field. Also making sure that it's possible to create Content Items with it using the API.
Fieldtype is not editable, so no scenario that it can be edited.

EZP-31311: Added ContentQuery generation

---

.travis.yml
Context/ConfigurationContext.php
Helper/ConfigurationEditor.php
behat_suites.yml
bin/.travis/prepare_multirepository_setup.sh
doc/features.md
features/setup/multirepository/multirepository.feature
tests/Helper/ConfigurationEditorTest.php

JIRA: https://jira.ez.no/browse/EZP-31313
This PR adds a feature that allows us to quickly set up multirepository config. The idea is simple:
1) add a new (valid) database connection
2) break the existing one (default) by setting an invalid password
3) create a new repository with the new connection
4) make all siteaccesses use the new repository
If anything tries to use the default repository the application will break, because the default connection is broken. Configuration after the feature is run:
```
doctrine:
dbal:
connections:
default:
driver: '%database_driver%'
host: '%database_host%'
port: '%database_port%'
dbname: '%database_name%'
user: '%database_user%'
password: ThisPasswordIsIncorrect
charset: '%database_charset%'
server_version: '%database_version%'
second_connection: …
```

EZP-31313: Added multirepository setup feature

---

bin/.travis/trigger_ci.sh

JIRA: https://jira.ez.no/browse/EZEE-2993
This PR reworks the script so that is works for Pull Requests to Page Builder repository.
There are two scenarios now:
1) there is no Page Builder dependency among given links: the script will create a branch and Pull Request in Page Builder
2) there is a Page Builder dependency among given links: the script will push a TMP commit to an existing branch
Other things:
1) Added colors 🎉 and improved some text formatting
2) Changed the commit message to `[TMP] Run regression` - it still runs the regression builds but can be easier detected and dropped when rebasing a PR

EZEE-2993: Changed regression script to work with Page Builder PRs as dependency

---

bin/.travis/trigger_ci.sh

`sed` program is different on Linux and OSX and there are some platform differences. One of them is the `-i` option, which causes the current script to fail on Linux.
Behaviour (described in comment on StackOverflow linked below):
```
This works with GNU sed, but not on OS X:
sed -i -e 's/foo/bar/' target.file
sed -i'' -e 's/foo/bar/' target.file
This works on OS X, but not with GNU sed:
sed -i '' -e 's/foo/bar/' target.file
```
Changing to solution suggested in https://stackoverflow.com/questions/5694228/sed-in-place-flag-that-works-both-on-mac-bsd-and-linux . This created a backup file, but the file is created in a tmp directory so I don't consider it an issue.
Thanks to @katarzynazawada for discovering it!

Changed sed usage to make regression script crossplatform

---

Command/GetPullRequestDataCommand.php
bin/.travis/trigger_ci.sh

JIRA: https://jira.ez.no/browse/EZP-31441
~~Will have to be rebased after https://github.com/ezsystems/BehatBundle/pull/131 is merged~~
Currently the script tries to read "_ezplatform_branch_for_behat_tests" for all repositories given, but it's not defined everywhere (for example in solr bundle). This causes the script to fail, as it cannot determine the metarepository branch for given PR.
This PR changes that - it's enough that at least one PR has Behat setup, so that the script can take data from that.*
*That means that it's still not possible to run regression for a single PR that has no Behat setup, but we need to tackle that in another issue, as it's not very likely.

EZP-31441: Handle undefined target metarepository branch

---

bin/ezbehat

If you look at the features run in https://travis-ci.com/github/ezsystems/ezplatform-page-builder/jobs/299676714#L1312-L1334 you can see that they are in wrong order:
```
1/23	✔	55 s 310 ms	/var/www/vendor/ezsystems/date-based-publisher/Features/PublishInTheFuture.feature
2/23	✔	6 s 515 ms	/var/www/vendor/ezsystems/ezplatform-admin-ui/features/standard/Authentication.feature
3/23	✔	1 min 45 s 313 ms	/var/www/vendor/ezsystems/ezplatform-admin-ui/features/standard/SystemInfo.feature
4/23	✔	3 min 7 s 243 ms	/var/www/vendor/ezsystems/ezplatform-page-builder/features/DynamicLandingPage/Blocks/Collection.feature
5/23	✔	1 min 50 s 698 ms	/var/www/vendor/ezsystems/ezplatform-admin-ui/features/standard/ContentCreation.feature
6/23	✔	1 min 31 s 147 ms …
```

Changed sorting order in listing Features for fastest

---

composer.json
src/bundle/Command/CreateLanguageCommand.php
src/bundle/Command/TestSiteaccessCommand.php
src/lib/API/Context/LimitationParser/LimitationParsersCollector.php

| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | [EZP-31007](https://jira.ez.no/browse/EZP-31007)
| **Type**                                   | improvement
| **Target eZ Platform version** | `v3.0.0`
| **BC breaks**                          | no
| **Tests pass**                          | TBD
| **Doc needed**                       | no
This PR replaces `ezpublish-kernel` with `ezplatform-kernel` and fixes dependency issues blocking package installation:
- `friends-of-behat/symfony-extension` is required in `2.1@beta` version supporting Symfony5 (no stable release available yet).
- `ezsystems/doctrine-dbal-schema` is required  in `1.0@dev` version due to Composer minimum …

EZP-31007: Replaced ezpublish-kernel with ezplatform-kernel

---

src/bundle/Command/GetPullRequestDataCommand.php
tests/Command/GetPullRequestDataCommandTest.php

JIRA: https://jira.ez.no/browse/EZP-31516
In Symfony 5 Commands are required to have an return code: https://symfony.com/blog/new-in-symfony-4-4-console-improvements#make-it-mandatory-to-return-the-command-exit-status
Adapting the command and adding a test to make sure it keeps working.

Adapted GetPullRequestDataCommand for Symfony5

---

Context/Object/UserContext.php

JIRA: https://jira.ez.no/browse/EZP-31542
Current code fails on PHP 7.4, as `$parsedLimitations` can be null:
```
` Notice: Trying to access array offset on value of type null in vendor/ezsystems/behatbundle/src/lib/API/Context/UserContext.php line 65`
```

Adjusted code for PHP7.4

---

features/personas/subtree_editor.feature

JIRA: https://jira.ez.no/browse/EZEE-3090
https://github.com/ezsystems/ezplatform-site-factory/pull/53 adds new permissions and `site/view` is among them - it's required if user wants to see the "Site" tab in upper menu.
Adjusting Subtree Editor permissions so that he can continue accessing it.
This permission won't be available in open source, so it will be useless/ignored in open source version.

Added site/view permission to SubtreeEditor

---

src/bundle/Resources/config/services/contexts.yaml

Related to [EZP-30465](https://jira.ez.no/browse/EZP-30465) as an intermediate step.
Fixed `PermissionResolver` injection into EzSystems\Behat\API\Context\TestContext (similar case like ezsystems/ezplatform-kernel/#43).
I think if there are no review objections and Behat passes, it should be ok to merge.

EZP-30465: Fixed PermissionResolver injection into Behat TestContext

---

Command/GetPullRequestDataCommand.php

Once we have a metarepository branch on which the tests should run we need to create a PR targeted to corresponding Page Builder branch.
Right now the Page Builder branch is detected using a hardcoded map (not good, we need to refactor it at some point), this PR updates the map for new stable branches.

Adjusted Page Builder branches map for new stable branch

---

bin/ezreport

JIRA: https://jira.ez.no/browse/EZP-31453
I've moved the code responsible for fixing name in the generated reports (`fix_allure_suites_names` function) to PHP code (moved to function: https://github.com/ezsystems/allure-behat/pull/10/files#diff-5e1b11234f6db9d5bf02356f36bf5403R473)

Moved suite name formatting to PHP code

---

API/ContentData/ContentDataProvider.php
API/Facade/ContentFacade.php
API/Facade/SearchFacade.php
Command/CreateExampleDataCommand.php
Command/CreateExampleDataManagerCommand.php
Event/TransitionEvent.php
Resources/config/services.yml
Resources/config/services/stages.yaml
Subscriber/AbstractProcessStage.php
Subscriber/CreateContentDraft.php
Subscriber/EditContent.php
Subscriber/PublishDraft.php
behat_suites.yml
features/setup/volume/content_items.feature
features/setup/volume/content_types.feature
features/setup/volume/languages.feature
features/setup/volume/users.feature

JIRA: https://jira.ez.no/browse/EZP-31525
The goal of this spike is to explore the options that we can use to generate millions of objects, large content structure, and multiple version.
A site with 300k Content Items: https://master-7rqtwti-hurg7yxf3msf4.eu-4.platformsh.site/
Login using admin/publish or one of the example editors:
- FrenchEditor1/Passw0rd-42
- PolishEditor3/Passw0rd-42
- SpanishEditor5/Passw0rd-42
(there are 50 Editors created for the tests).
Feel free to experiment, you can create/edit etc. - just please don't delete large Subtrees and don't mess with existing permissions (but you can create new Users if you want to).
We will be using Enterprise version for the tests (both on v2 and v3).
It is be possible to generate lots of data using:
- REST
- Behat
- PHP API
- SQL …

[SPIKE] Volume testing

---

Command/CreateExampleDataCommand.php

Follow-up to https://github.com/ezsystems/BehatBundle/pull/151 - trailing comma in function call is a valid language construct in PHP 7.3 - https://laravel-news.com/php-trailing-commas-functions -  but not in PHP 7.1, which is supported by eZ Platform 2.5.
Failing build: https://travis-ci.org/github/ezsystems/ezpublish-kernel/jobs/684633871#L781
Thanks to @alongosz for finding that!

Removed trailing comma

---

bin/.travis/trigger_ci.sh

I'm not sure if this is an issue only for me, but each time the script calls `git` on remote repository, I'm being asked for my GitHub credentials. It's possible that you just have them saved somewhere (e.g. by using the [credential helper](https://help.github.com/en/github/using-git/caching-your-github-password-in-git)). This is not the best idea, we should use ssh when accessing private repositories. Though if password is stored in keychain or expires after some short period of time, it's not that bad either.
Please notice also that we've been using HTTP instead of HTTPS in the script. So at some point, before redirection to HTTPS credentials might be sent over an unsecure connection.
Based on @mnocon's suggestion I was able to delegate the responsibility of choosing an authentication …

[Travis] Regression script: Fixed repository URIs to use SSH instead of HTTP

---

features/personas/subtree_editor.feature

The first step creates a Content Type with `dedicatedFolder` Content Type identifier:
```
I create a "DedicatedFolder" Content Type in "Content" with "dedicatedFolder" identifier
```
But the next steps (`I create "DedicatedFolder" Content items in root in "eng-GB"`) are using Content Type Name instead - it works on mysql (which seems to ignore the difference in casing) but fails on PostgreSQL. 
The "I create..." step expects contentTypeIdentifier, see:https://github.com/ezsystems/BehatBundle/blob/master/src/lib/API/Context/ContentContext.php#L41

Corrected contentTypeIdentifier for case sensitive systems

---

src/bundle/Resources/config/services/contexts.yaml
src/lib/API/Context/TrashContext.php

`@injectService` has been removed in v3, we're using https://github.com/FriendsOfBehat/SymfonyExtension/releases instead.
Required by: https://github.com/ezsystems/ezplatform-workflow/pull/152

Fixed invalid merge: added TrashContext service definition

---

composer.json
src/lib/API/Facade/ContentFacade.php
src/lib/Browser/Context/BrowserContext.php
src/lib/Browser/Page/FrontendLoginPage.php
src/lib/Core/Context/TimeContext.php

JIRA: https://issues.ibexa.co/browse/EZP-32103
Changes required by https://github.com/ezsystems/ezplatform-http-cache/pull/138
Couple of things here:
1) Added a new Context (TimeContext) that allows to wait a couple of seconds
2) Added a check that the login action is successful - we should be redirected after the login action to another page
3) As I've played with the Chromium a bit I've noticed that the format for HTTP headers is different - I've decided to include support for it in this PR 😄 
4) And the most important change: HTTP flushing. Here's a glimpse into our HTTP cache:
When we want to purge cache: https://github.com/ezsystems/ezplatform-http-cache/blob/master/src/PurgeClient/VarnishPurgeClient.php#L27
we call the `invalidateTags` method. We're using the `PURGEKEYS` way, so …

EZP-32103: Add Varnish integration tests

---

src/lib/Core/Environment/EnvironmentConstants.php

Right now Enterprise tests are failing with:
```
Behat\Testwork\Call\Exception\FatalThrowableError: Fatal error: Undefined class constant 'ENTERPRISE' in vendor/ezsystems/behatbundle/src/lib/Core/Environment/EnvironmentConstants.php:44
```
this PR fixes that.
Working proof: https://travis-ci.com/github/ezsystems/ezplatform-page-builder/builds/210398845 (the first two jobs passed which wouldn't happen otherwise).

Fixed installation type detection

---

src/lib/Core/Environment/Environment.php

Right now tests running on Flex are failing with:
```
╳  Notice: Undefined index: ibexa/website-skeleton in vendor/ezsystems/behatbundle/src/lib/Core/Environment/Environment.php line 71
```
beucase the condition in `isInstalledFromMetarepository` is too broad.
Proof that it's working:
correctly running build in https://travis-ci.com/github/ezsystems/ezplatform-admin-ui/builds/211144857 🎉

Fixed installation type detection for Flex

---

src/bundle/Command/CreateExampleDataCommand.php
src/bundle/Command/CreateExampleDataManagerCommand.php
src/bundle/Command/CreateLanguageCommand.php
src/bundle/Command/GetPullRequestDataCommand.php
src/bundle/Command/TestSiteaccessCommand.php

> JIRA: [EZP-32259](https://jira.ez.no/browse/EZP-32259)
Replaced "ezplatform" commands namespace with "ibexa".
<table><tbody><tr><td><strong>Old name</strong></td><td><strong>New name</strong></td></tr><tr><td><code>ezplatform:tools:create-data</code></td><td><code>ibexa:behat:create-data</code></td></tr><tr><td><code>ezplatform:tools:generate-items</code></td><td><code>ibexa:behat:generate-items</code></td></tr><tr><td><code>ez:behat:create-language</code></td><td><code>ibexa:behat:create-language</code></td></tr><tr><td><code>ezplatform:tools:get-pull-request-data</code></td><td><code>ibexa:behat:get-pull-request-data</code></td></tr><tr><td><code>ez:behat:siteaccess</code></td><td><code>ibexa:behat:test-siteaccess</code></td></tr></tbody></table>
Requires …

EZP-32259: Replaced "ezplatform" commands namespace with "ibexa"

---

bin/.travis/trigger_ci.sh

`ezplatform:tools:get-pull-request-data` is deprecated, we should use `ibexa:behat:get-pull-request-data`.
In this case it's not only an issue of fixing a deprecation - we're parsing the command output directly, so the deprecation warning is parsed as well and the script fails to detect the correct branch to use.

Updated deprecated command name

---

composer.json
src/bundle/DependencyInjection/eZBehatExtension.php

Changed how the installation type (OSS, Content, Experience, Commerce) is detected:
the solution using post-install package works for Flex installations, but breaks for metarepository installs.
This approach should work for both of them.
Failing build:
https://travis-ci.com/github/ezsystems/ezplatform/jobs/489613579
```
PHP Fatal error:  Uncaught TypeError: Return value of Ibexa\Platform\PostInstall\IbexaProductVersion::getInstalledProduct() must be of the type string, bool returned in /var/www/vendor/ibexa/post-install/src/lib/IbexaProductVersion.php:44
Stack trace:
#0 /var/www/vendor/ezsystems/behatbundle/src/bundle/DependencyInjection/eZBehatExtension.php(36): Ibexa\Platform\PostInstall\IbexaProductVersion::getInstalledProduct()
#1 …
```

Changed how installation type is detected

---

.gitignore
src/bundle/Command/GetPullRequestDataCommand.php
tests/Command/GetPullRequestDataCommandTest.php

Backporting the unit tests fix, as promised in https://github.com/ezsystems/BehatBundle/pull/174

Made GitHub token optional for getting PR data

---

composer.json
src/bundle/Controller/RenderController.php
src/bundle/Resources/config/services.yaml
src/bundle/Resources/config/services/contexts.yaml
src/bundle/Resources/config/services/controllers.yaml
src/bundle/Resources/views/tests/cache/embed_esi.html.twig
src/bundle/Resources/views/tests/cache/embed_no_esi.html.twig
src/bundle/Resources/views/tests/cache/embedded.html.twig
src/lib/Browser/Context/BrowserContext.php
src/lib/Browser/Context/FrontendContext.php
src/lib/Core/Context/TimeContext.php

JIRA: https://issues.ibexa.co/browse/IBX-116
Required by: https://github.com/ezsystems/ezplatform-http-cache/pull/149
This PR adds two things:
1) More time-related steps to TimeContext - it's possible to measure time of execution of steps by enclosing them between `I start measuring time` and one of `the action took no longer than N seconds` or `the action took longer than N seconds`.
2) Twig templates and Controllers used to enrich the default ViewController (see related PR and https://doc.ibexa.co/en/latest/guide/controllers/#enriching-viewcontroller-with-a-custom-controller for more info how it works)
The templates and Controller allow us to render a Content Item and an embedded Content item in it (using the rendering method that we choose - "standard" and "ESI" is used here). The long …

IBX-116: More integration tests for HTTP cache

---

features/personas/add_location.feature

**JIRA**: https://issues.ibexa.co/browse/IBX-579
Behatbundle part of the test checking whether user with Content Type limitation on content/create policy can add another location.
Related PRs:
https://github.com/ezsystems/ezplatform-admin-ui/pull/1783

IBX-579: Behat coverage for user with CT limitation adding location

---

src/lib/Browser/Routing/Router.php

Routes returned from the `getRoute` method will be automatically prefixed with a forward slash if they do not contain it already.
The slash prefix is required by tests running using Map\Host matcher.
Required by:
https://github.com/ezsystems/ezplatform-page-builder/pull/787

Changed Router to always prefix routes with slash

---

src/lib/Browser/Element/Criterion/ChildElementTextCriterion.php

Failure: https://travis-ci.com/github/ezsystems/ezplatform-form-builder/jobs/524393788
When ChildElementText fails, there's an error:
```
| SingleLine Custom Form   | Single line input   | Custom single line   |
Notice: Array to string conversion in vendor/ezsystems/behatbundle/src/lib/Browser/Element/Criterion/ChildElementTextCriterion.php line 58
Screenshot has been taken. Open image at https://res.cloudinary.com/ezplatformtravis/image/upload/v1626268366/screenshots/60eee2ce4a74d935515446-vendor_ezsystems_ezplatform-form-builder_features_formfieldconfiguration_feature_35_txmj6k.png
```
The result from array_merge should not be appended to the results variable but replace it.
With this change the error message is correct:
```
Could not find element wih text: 'Single line inputasdasd' …
```

Fixed ChildElementTextCriterion error message

---

src/lib/API/ContentData/FieldTypeData/SelectionDataProvider.php

| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          |  https://issues.ibexa.co/browse/IBX-160
| **Type**                                   | tests
| **Target version** | 8.3
| **BC breaks**                          | no
| **Tests pass**                          | no
| **Doc needed**                       | no
This PR requires https://github.com/ezsystems/ezcommerce-shop/pull/319
This PR adds configuration for 'sesspecificationstype' field which occurs in ezlandingpage field - if 'sesspecificationstype' field is empty (and usually it is, as it is not mandatory) a whole JSON is injected there (this is done now in https://github.com/ezsystems/ezcommerce-shop/pull/319 …

[Behat] IBX-160 - added configuration for 'sesspecificationstype' field in Product content type

---

src/lib/Browser/Element/BaseElement.php
tests/Browser/Element/BaseTestCase.php
tests/Browser/Element/ElementTest.php

https://issues.ibexa.co/browse/IBX-264
~~Requires: https://github.com/ezsystems/BehatBundle/pull/194 - will need to be rebased after it's merged and target branch will be changed to 8.3~~
This PR changes how the `find` method works.
You can specify additional conditions using Locators - for example you can use `VisibleCSSLocator` to add a condition that an element must be visible to be found.
Given a simple site with 2 buttons, `InvisibleButton` and `VisibleButton` (`InvisibleButton` is higher in HTML hierarchy).
When you search for a button using:
`$this->getHTMLPage()->find(new VisibleCSSLocator('myButton', 'button')`
Current behaviour:
1) Mink find the first button in the HTML page (the `InvisibleButton` button).
2) Then we check if this element matches the Locator criteria (in our …

Change find behaviour

---

behat_ibexa_commerce.yaml
behat_ibexa_content.yaml
behat_ibexa_experience.yaml
features/personas/subtree_editor.feature
src/lib/Browser/Element/Criterion/LogicalOrCriterion.php
src/lib/Browser/Page/LoginPage.php
tests/Browser/Element/Criterion/LogicalOrCriterionTest.php

JIRA: https://issues.ibexa.co/browse/IBX-753
~~Requires https://github.com/ezsystems/BehatBundle/pull/194 to be merged first and then will be rebased to 8.3 branch.~~
1) Added tests from ezplatform-user and ezplatform-page-fieldtype to regression suites
2) On Commerce the Subtree editor tests are failing, because the design requires user to have content/read permissions to itself.
Location ID 139 is the Subtree Editor user himself.
I've decided to add it, as it's the quickest way to solve this problem and IMHO it does not change the Subtree Editor scenarios a lot (they still test the things they are supposed to).
3) The current Login page is not able to login on Commerce frontend, because the Login button selector is too broad. 
I haven't found any way to narrow it down (the frontend …

[Regression] Enabled more tests for Ibexa DXP

---

behat_ibexa_content.yaml
behat_ibexa_experience.yaml

Follow-up to https://github.com/ezsystems/BehatBundle/pull/193 - I've added tests from ezplatform-user, but not all Context classes are present in regression suites to run them.
Failures:
https://app.travis-ci.com/github/ezsystems/ezplatform-workflow/jobs/527508654
Content suite:
```
--- Use --snippets-for CLI option to generate snippets for following content suite steps:
Given I create a user "UnsupportedPasswordUser" with last name "User" in group "Anonymous Users"
Then the url should match "/site/user/forgot-password/migration"
And I should see "Your password has expired"
```
https://app.travis-ci.com/github/ezsystems/ezplatform-page-builder/jobs/527508678
Experience suite:
```
--- Use --snippets-for CLI option to generate snippets for following experience suite steps:
Given I create a …
```

Added missing Contexts to Experience and Content regression suites

---

src/lib/Browser/Element/Criterion/ElementAttributeCriterion.php
src/lib/Browser/Element/Element.php
tests/Browser/Element/Criterion/ElementAttributeCriterionTest.php

Added as part of https://issues.ibexa.co/browse/IBX-650, used in ezsystems/ezplatform-admin-ui#1808
Can be used to get an Element from a Collection based on value of a given attribute. I need it for master, but it should be useful for 8.3 as well, hence the backport.
You can see that CI passes for master: https://github.com/ezsystems/BehatBundle/pull/197

IBX-650: Added ElementAttributeCriterion

---

src/lib/Browser/Element/ElementCollection.php
tests/Browser/Element/ElementCollectionTest.php

When a collection is empty (`findAll` did not return any elements) the current results of calling `first` and `last` methods are:
- first: `Return value of Ibexa\Behat\Browser\Element\ElementCollection::first() must implement interface Ibexa\Behat\Browser\Element\ElementInterface, none returned`
- last: `Return value of Ibexa\Behat\Browser\Element\ElementCollection::last() must implement interface Ibexa\Behat\Browser\Element\ElementInterface, bool returned`
This PR fixes it - when the collection is empty an exception will be thrown instead.

Fixed behaviour of first and last on empty collection

---

src/lib/Browser/Element/Condition/ElementsCountGreaterThanCondition.php
tests/Browser/Element/Condition/ElementsCountGreaterThanConditionTest.php

This PR adds a new Condition that checks whether the actual numbers of Elements is greater than the given one.
Sometimes it's useful to make sure that enough elements were found without specyfing the exact amount (which can vary depending on product edition etc.).
Example usage:
```
$this->getHTMLPage()
->setTimeout(5)
->waitUntilCondition(
new ElementsCountGreaterThanCondition($this->getHTMLPage(), $this->getLocator('buttons'), 5)
)
->findAll(...) // continue only after at least 6 buttons have been found
```
It's named after the PHPUnit Assertion: https://phpunit.readthedocs.io/en/9.5/assertions.html#assertgreaterthan and works in the same way.

Added ElementsCountGreaterThanCondition

---

src/bundle/Resources/encore/ez.config.manager.js

PR is connected to: https://github.com/ezsystems/ezplatform-admin-ui/pull/1835
This PR adds drag-mock library to _ezplatform-admin-ui-content-type-edit-js_ to avoid : ` RuntimeException: drag-mock library has to be added to the page in order to use this method. ` errors.

[Behat][Redesign] Fix for drag-mock library

---

API/Facade/ContentTypeFacade.php

Failing build: https://app.travis-ci.com/github/ezsystems/ezplatform/jobs/537291945
Error:
```
Exception: Could not load the Content type after publishing. in vendor/ezsystems/behatbundle/EzSystems/BehatBundle/API/Facade/ContentTypeFacade.php:92
Stack trace:
#0 vendor/ezsystems/behatbundle/EzSystems/BehatBundle/API/Facade/ContentTypeFacade.php(49): EzSystems\BehatBundle\API\Facade\ContentTypeFacade->assertContentTypeExistsInGroup()
```
In https://github.com/ezsystems/ezpublish-kernel/pull/3114 the persistance tags have been changed and since then the Content Type cache purge no longer works.
I've adapted the code based on what's in the kernel.
Old code:
https://github.com/ezsystems/ezpublish-kernel/blob/v7.5.21/eZ/Publish/Core/Persistence/Cache/ContentTypeHandler.php#L272-L287
Current …

Adapted clearing persistence tags after the refactoring

---

src/lib/Browser/Element/Criterion/ElementTextFragmentCriterion.php
tests/Browser/Element/Criterion/ElementTextFragmentCriterionTest.php

This PR adds a small feature that allows you to get an element based on a fragment of its text.
Real life example - headers in some tables:
Let's say you want to get the header for Stage "Draft" you can't use `ElementTextCriterion`, because the number of items in that stage varies.
Currently you'd need to do something like:
```php
$searchedHeader = null;
$headers = $this->getHTMLPage()->findAll($headerLocator);
foreach ($headers as $header) {
if (false !== strpos($headers->getText(), 'Draft') {
$searchedHeader = $header;
}
}
$searchedHeader->click(); // or something else
```
With the new criterion you can do it like this:
```php
$this->getHTMLPage()
->findAll($headerLocator)
->getByCriterion(new ElementTextFragmentCriterion('Draft'))
->click();
```
ElementTextFragmentCriterion will match …

Added ElementTextFragmentCriterion

---

bin/.travis/prepare_multirepository_setup.sh
features/setup/multirepository/multirepository.feature

This is required, because some installers use Ibexa Migrations which create items in the database using our API. Because the API is used it's not enough to drop the database - there are still some leftovers in the SPI cache which are causing issues. We use `CACHE_POOL` if defined (for example: when redis is defined: https://github.com/ibexa/docker/blob/main/docker/redis.yml#L13), otherwise we fallback to the default value (https://github.com/ibexa/content-skeleton/blob/v3.3.10/.env#L43)
- it's required to have multirepository tests on the Content edition
- The Site Factory connection can be removed, because it's defined in another file in v3.3: https://github.com/ibexa/experience-skeleton/blob/v3.3.10/config/packages/ezplatform_site_factory.yaml#L18-L29
- In the product the connection is …

Change multirepository setup

---

src/bundle/Resources/encore/ez.config.manager.js
src/bundle/Resources/public/js/scripts/transition-listener.js
src/lib/Browser/Element/Condition/ElementTransitionHasEndedCondition.php
src/lib/Browser/Element/Debug/Highlighting/BaseElement.php
tests/Browser/Element/BaseTestCase.php
tests/Browser/Element/Condition/ElementExistsConditionTest.php
tests/Browser/Element/Condition/ElementNotExistsConditionTest.php
tests/Browser/Element/Condition/ElementTransitionHasEndedConditionTest.php
tests/Browser/Element/Condition/ElementsCountConditionTest.php
tests/Browser/Element/Condition/ElementsCountGreaterThanConditionTest.php
tests/Browser/Element/Criterion/ChildElementTextCriterionTest.php

Add a new condition that allows us to detect in browser tests when a CSS transition has ended. An event listener is added that fires when a transition ends and adds a special class (`ibexa-selenium-transition-ended`) that we can later detect in tests.
https://user-images.githubusercontent.com/10993858/137711537-f74e5ca8-6d38-4956-93d2-8120a34914ad.mp4
https://github.com/ezsystems/ezplatform-admin-ui/pull/1969/files
I've added the event listener and reorganised config manager to make it a bit more readable.
This PR is for master, because I want to make sure it solves the issue present there - if it works then I will backport it to 8.3 branch.

Added ElementTransitionHasEnded condition

---

src/bundle/Resources/public/js/scripts/transition-listener.js
src/lib/Browser/Element/Condition/ElementTransitionHasEndedCondition.php
tests/Browser/Element/Condition/ElementTransitionHasEndedConditionTest.php

Follow up to https://github.com/ezsystems/BehatBundle/pull/220 which will allow us to detect if the transition has been started at all.
This makes the Condition easier to use:
1) If the transition has started but did not end in time the error message will be similar to:
```
And I go to "Content structure" in "Content" tab                      # Ibexa\AdminUi\Behat\BrowserContext\NavigationContext::iGoToTab()
Transition has not ended for element with CSS locator 'menuFirstLevel': '.ibexa-main-menu__navbar--first-level'. Timeout value: 3 seconds. (Ibexa\Behat\Browser\Exception\TimeoutException)
```
2) If the transition has not started at all (because the Condition is used on an incorrect element or too early) then the error message will be:
```
And I go to "Content structure" in "Content" …
```

Mark items for which the transition has started

---

src/lib/API/Facade/UserFacade.php

Issue: currently you can't use a step like this one:
https://github.com/ezsystems/ezplatform-user/blob/master/features/browser/signIn.feature#L6
with groups like "Administrator users" because current code fails to find them.
Error message:
```
Notice: Undefined offset: 0 in vendor/ezsystems/behatbundle/src/lib/API/Facade/UserFacade.php line 137
```
Solution:
We can't rely solely on `Field` criterion, because some system user groups are missing the correct value in `sort_key_string` in SQL installer and LSE fails to find them. This PR adds a fallback method for User Group searching (which will be used when the primary one fails).

Fixed user group searching for system user groups

---

bin/.travis/prepare_multirepository_setup.sh

JIRA: https://issues.ibexa.co/browse/IBX-1290
Required by:
https://github.com/ezsystems/ezplatform-admin-ui/pull/1999
1) Github Actions runner is not a TTY by defalt (https://github.com/actions/runner/issues/241), so I've added the `-T` option (https://docs.docker.com/compose/reference/exec/)

Adapted multirepo setup to GA

---

behat_ibexa_commerce.yaml
behat_ibexa_content.yaml
behat_ibexa_experience.yaml
behat_ibexa_oss.yaml

Removing these whitespaces gets rid of this error:
```
Deprecated: Tags with whitespace are deprecated and may be removed in a future version in /Users/mareknocon/Desktop/Sites/v3_2/vendor/behat/gherkin/src/Behat/Gherkin/Filter/TagFilter.php on line 38
```
Also, somehow, it gets rid of this error when running the test locally:
```
1.0005   62771536  18. trigger_error() /Users/mareknocon/Desktop/Sites/v3_2/vendor/behat/gherkin/src/Behat/Gherkin/Filter/TagFilter.php:38
In NativeFileSessionHandler.php line 52:
Warning: ini_set(): Headers already sent. You cannot change the session module's ini settings at this time
```
Behat doc reference: https://docs.behat.org/en/v2.5/guides/6.cli.html#gherkin-filters
Tested locally and in https://app.travis-ci.com/github/ezsystems/ezplatform-page-builder/b …

Removed whitespace from tag filters

---

features/personas/subtree_editor.feature
src/lib/API/Context/LimitationParser/LocationLimitationParser.php

Adding workaround for failing personas tests because of lack of permissions to read the Taxonomy Content Item.
When the issue is fixed this commit will have to be reverted.
Tested in:
https://github.com/ibexa/oss/pull/28
https://github.com/ibexa/content/pull/23

Added workaround for taxonomy

---

.github/workflows/ci.yaml
composer.json

Things done:
1) Removed ignoring PHP requirements on CI
2) Bumped Faker to a version supporting PHP 8 (`fzaninotto/Faker` is no longer developed: https://github.com/fzaninotto/Faker, `FakerPHP/Faker` is the new organisation - https://github.com/FakerPHP/Faker)
3) Added required packages to require-dev - they are unstable dependencies of dependencies and need to be added directly (because there are no stable releases supporting PHP 8 yet)

[CI] Removed ignore-platform-req from PHP 8 installation

---

features/personas/subtree_editor.feature
src/lib/Core/Behat/ArgumentParser.php
tests/Core/Behat/ArgumentParserTest.php

The location of the Taxonomy menu item has changed - it was `taxonomy/tags`, but now it's `/taxonomy/tags/root`
It's not enough to change it in the Scenario, because the `parseUrl` method replaced every `root` keyword occurance with an empty space - it's used to take into account that the name of the root Content Item can be different accross different product editions. Example usage:
https://github.com/ibexa/admin-ui/blob/f44128683057ddb8a09c572423113d999c988592/features/personas/SubtreeEditor.feature#L23-L24
It's all great, but because of that `/taxonomy/tags/root` becomes `taxonomy/tags` and we're back to square one 🙃 
I've changed ArgumentParser to change the root keyword only when it's in the beggining of the string - when it's later in the path it's left unchanged.
Added tests to …

Fixed taxonomy location path

---

bin/ezbehat

Composer 2.2.2 changes the working directory when binaries are executed:
https://github.com/composer/composer/issues/10389
https://github.com/composer/composer/pull/10402
It's also mentioned in the release notes for Composer 2.2.2:
https://github.com/composer/composer/releases/tag/2.2.2
```
Added COMPOSER_BIN_DIR env var and _composer_bin_dir global containing the path to the bin-dir for binaries. Packages relying on finding the bin dir with $BASH_SOURCES[0] will need to update their binaries (#10402)
```
This PR updates our ezbehat runner so that it relies on `COMPOSER_BIN_DIR`, not `BASH_SOURCES` env variable.

Adapted ezbehat runner to Composer 2.2

---

src/lib/API/Facade/ContentFacade.php

https://doc.ibexa.co/en/latest/api/public_php_api_creating_content/#translating-content
```
To translate a Content item to a new language, you need to update it and provide a new initialLanguageCode:
```
Using this code for translations was semi-broken before this change, because the new `initialLanguageCode` was not set and the system did not register it fully as a new translation.

Fixed translating Content by setting initialLanguageCode

---

src/bundle/Resources/config/services/limitation_parsers.yaml
src/lib/API/Context/ContentTypeContext.php
src/lib/API/Context/LimitationParser/FieldGroupLimitationParser.php
src/lib/Browser/Assert/Debug/Interactive/ElementAssert.php
src/lib/Browser/Assert/ElementAssert.php
src/lib/Browser/Assert/ElementAssertInterface.php

JIRA: https://issues.ibexa.co/browse/IBX-1481
Related PR's:  https://github.com/ezsystems/ezplatform-workflow/pull/247 & https://github.com/ezsystems/ezplatform-admin-ui/pull/2022 
Successful Travis build: https://github.com/ezsystems/ezplatform-page-builder/pull/920
This PR provides the possibility to define in which field group the field is added to during creation of Content Type.
In this example _Name_ field is in Content field group, and _Description_ field is in Metadata field group.

[Behat] IBX-1481 Added field group handling during field adding

---

behat_ibexa_commerce.yaml
behat_ibexa_experience.yaml

This PR fixes lack of LanguageContext for Experience & Commerce editions. Example error - https://github.com/ibexa/experience/runs/4928762776?check_suite_focus=true
>  --- Use --snippets-for CLI option to generate snippets for following setup-experience suite steps:
> 
>     Given Language "German" with code "ger-DE" exists
>     And Language "French" with code "fre-FR" exists

Added LanguageContext to Experience & Commerce

---

.github/workflows/browser-tests.yaml
features/setup/loginMethods/email_provider.feature

Adjusting tests to avoid the:
```
Executing script cache:clear [KO]
[KO]
Script cache:clear returned with error code 1
!!  
!!  In SecurityExtension.php line 713:
!!                                                                                 
!!    Not configuring explicitly the provider for the "guard" listener on "ibexa_  
!!    front" firewall is ambiguous as there is more than one registered provider.  
!!                                                                                 
!!  
```
```
In SecurityExtension.php line 713:
Not configuring explicitly the provider for the "form_login" listener on "ibexa_front" firewall is ambiguous as there is more than one registered provider.  
```
errors on CI
Ive also changed the CI setup here to run the full OSS setup during build …

Adjust login provider
